version: '3.8'

services:
  flask:
    build:
      context: .
    container_name: flask_app_runner
    expose:
      - "8000"
    restart: on-failure
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - flask-network

  nginx:
    image: nginx:latest
    container_name: reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask
    networks:
      - flask-network

networks:
  flask-network:
    name: flask-network
